name: Docs
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Install Python
      uses: actions/setup-python@v2

    - name: Install prerequisites
      run: pip install -e .[dev]
      
    - name: Build & Deploy Docs
      shell: bash
      run: |
        git status
        git config --local user.email "github-actions-bot@users.noreply.github.com"
        git config --local user.name "Github Actions Bot"
        
        cd docs/
        make html
        
        git checkout gh-pages

        mv docs/build/html/_static docs/build/html/static
        mv docs/build/html/* .
        mv static/ .static/
        shopt -s extglob
        rm -rf !(README.md|*.html|*.js|*.json)
        mv .static/ _static/

        git add .
        git commit -m "Update docs for commit ${GITHUB_SHA}"
        git push
