name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install 
        run: pip install -e .[dev]

      - name: Unit tests
        run: coverage run --source=flashcards_server -m pytest --random-order

      - name: Coveralls.io
        run: |
          coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_SERVICE_NAME: 'github'
